/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IconCommunity: typeof import('./../src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./../src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./../src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./../src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./../src/components/icons/IconTooling.vue')['default']
    LayoutContent: typeof import('./../src/components/layouts/components/layout-content.vue')['default']
    LayoutFooter: typeof import('./../src/components/layouts/components/layout-footer.vue')['default']
    LayoutHeader: typeof import('./../src/components/layouts/components/layout-header.vue')['default']
    Layouts: typeof import('./../src/components/layouts/index.vue')['default']
    LayoutSidebar: typeof import('./../src/components/layouts/components/layout-sidebar.vue')['default']
    LayoutTabbar: typeof import('./../src/components/layouts/components/layout-tabbar.vue')['default']
    Loading: typeof import('./../src/components/common/Loading.vue')['default']
    Logo: typeof import('./../src/components/common/Logo.vue')['default']
    Modal: typeof import('./../src/components/modal/modal.vue')['default']
    NaiveProvider: typeof import('./../src/components/common/NaiveProvider.vue')['default']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarCollapseButton: typeof import('./../src/components/layouts/components/sidebar-collapse-button.vue')['default']
    SidebarFixedButton: typeof import('./../src/components/layouts/components/sidebar-fixed-button.vue')['default']
    Spinner: typeof import('./../src/components/common/Spinner.vue')['default']
  }
}
